---
specfile_path: pycharm-community.spec
downstream_package_name: pycharm-community
actions:
  post-upstream-clone: "bash download_sources.sh"
jobs:
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
      - fedora-stable
